#!/bin/bash

filename=$1
res=${filename:5:3}

echo "Residue $res"

if [[ -s "$res.lib" ]]; then
      echo "    already done: skipping"
      exit 0
else
      /bin/rm -f $res.lib
fi

if [ ! -f "$res.mol2" ]; then
      echo "    no mol2 file: skipping"
      exit 0
fi

cat <<EOF > tleap.in
mxx = loadMol2 $res.mol2
saveOff mxx mxx.lib
quit
EOF

$AMBERHOME/bin/tleap -f tleap.in > tleap.log

sed "s/mxx/$res/" mxx.lib > $res.lib 

/bin/rm mxx.lib tleap.in tleap.log
