#!/bin/bash

#  update all Amber files with new contributions.
#    suggestion: first do this in the "amber" branch; then if everything
#    looks OK, merge into master

# for i in a b c d e f g h i j k l m n o p q r s t u v w x y z; do
for i in b c; do

  cd $i
  for j in data_???.cif; do
    ../gcif_to_mol2 $j
  done
  cd ..

done
